export const STATE_NAME = 'COMMON';

export const GET_CITIES = 'GET_CITIES';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';

export const GET_PHONE_CODES = 'GET_PHONE_CODES';
export const GET_PHONE_CODES_SUCCESS = 'GET_PHONE_CODES_SUCCESS';

export const GET_CATEGORIES_SKILLS = 'GET_CATEGORIES_SKILLS';
export const GET_CATEGORIES_SKILLS_SUCCESS = 'GET_CATEGORIES_SKILLS_SUCCESS';

export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';

export const REMOVE_FILE = 'REMOVE_FILE';
export const REMOVE_BULK_FILE = 'REMOVE_BULK_FILE';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPDATE_FILE = 'UPDATE_FILE';
export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';

export const GET_ROLE_EMPLOYEE = 'GET_ROLE_EMPLOYEE';
export const GET_ROLE_EMPLOYEE_SUCCESS = 'GET_ROLE_EMPLOYEE_SUCCESS';

export const GET_CONFIGURATION = 'GET_CONFIGURATION';
export const GET_CONFIGURATION_SUCCESS = 'GET_CONFIGURATION_SUCCESS';

export const GET_NOTIFICATION_PAGING = 'GET_NOTIFICATION_PAGING';
export const GET_NOTIFICATION_PAGING_SUCCESS =
  'GET_NOTIFICATION_PAGING_SUCCESS';

export const COUNT_UNREAD_NOTIFICATIONS = 'COUNT_UNREAD_NOTIFICATIONS';
export const COUNT_UNREAD_NOTIFICATIONS_SUCCESS =
  'COUNT_UNREAD_NOTIFICATIONS_SUCCESS';

export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const MARK_ALL_NOTIFICATION_READ = 'MARK_ALL_NOTIFICATION_READ';
export const UPDATE_NOTIFICATION_DATA = 'UPDATE_NOTIFICATION_DATA';

export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const DELETE_ALL_NOTIFICATION = 'DELETE_ALL_NOTIFICATION';

export const GENERATE_API_KEY = 'GENERATE_API_KEY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_SKILLS = 'GET_SKILLS';
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS';
