export const STATE_NAME = 'PROJECT';

const prefix = STATE_NAME + '_';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';

export const GET_ALL_PROJECT = 'GET_ALL_PROJECT';
export const GET_ALL_PROJECT_SUCCESSFUL = 'GET_ALL_PROJECT_SUCCESSFUL';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_OWN_PROJECTS_SUCCESS = 'GET_OWN_PROJECTS_SUCCESS';
export const GET_OWN_PROJECT_JOBS = 'GET_OWN_PROJECT_JOBS';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL';
export const CREATE_PROJECT_DOCUMENTS = 'CREATE_PROJECT_DOCUMENTS';
export const PROJECT_VALIDATE_NAME = 'PROJECT_VALIDATE_NAME';
export const GET_OWN_PROJECT = 'GET_OWN_PROJECT';
export const GET_OWN_PROJECT_SUCCESSFUL = 'GET_OWN_PROJECT_SUCCESSFUL';
export const INVITE_CLIENT_TO_PROJECT = 'INVITE_CLIENT_TO_PROJECT';

export const TOGGLE_FINANCE_REPORT_MODAL = 'TOGGLE_FINANCE_REPORT_MODAL';

export const GET_ALL_FINANCE_REPORT = {
  LOADING: 'GET_ALL_FINANCE_REPORT_LOADING',
  PROCESS: 'GET_ALL_FINANCE_REPORT_PROCESS',
  SUCCESS: 'GET_ALL_FINANCE_REPORT_SUCCESS',
  SET_TOTAL_COST: 'GET_ALL_FINANCE_REPORT_TOTAL_COST',
  SET_TOTAL_SELL: 'GET_ALL_FINANCE_REPORT_TOTAL_SELL',
};

export const SAVE_FINANCE_REPORT = 'SAVE_FINANCE_REPORT';

export const GET_SHARED_PROJECT_DETAIL = 'GET_SHARED_PROJECT_DETAIL';

export const GET_EMPLOYEE_PROJECT = prefix + 'GET_EMPLOYEE_PROJECT';
export const GET_EMPLOYEE_PROJECT_SUCCESSFUL =
  prefix + 'GET_EMPLOYEE_PROJECT_SUCCESSFUL';
