export const STATE_NAME = 'PARTNER_ADMIN';

export const GET_PARTNER_ADMIN = 'GET_PARTNER_ADMIN';
export const GET_PARTNER_ADMIN_SUCCESS = 'GET_PARTNER_ADMIN_SUCCESS';

export const GET_RELATIONSHIP_PARTNER = 'GET_RELATIONSHIP_PARTNER';
export const GET_RELATIONSHIP_PARTNER_SUCCESS =
  'GET_RELATIONSHIP_PARTNER_SUCCESS';
