export const STATE_NAME = 'PARTNER';

export const GET_PARTNER_ALL = 'GET_partners/all';

export const GET_PARTNER_PROFILE_BY_SUBDOMAIN =
  'GET_PARTNER_PROFILE_BY_SUBDOMAIN';
export const GET_PARTNER_PROFILE = 'GET_PARTNER_PROFILE';
export const GET_PARTNER_PROFILE_SUCCESS = 'GET_PARTNER_PROFILE_SUCCESS';

export const GET_PARTNER_ASSIGNED_PROJECTS = 'GET_PARTNER_ASSIGNED_PROJECTS';
export const GET_PARTNER_ASSIGNED_PROJECTS_SUCCESS =
  'GET_PARTNER_ASSIGNED_PROJECTS_SUCCESS';

export const GET_PARTNER_ASSIGNED_JOBS = 'GET_PARTNER_ASSIGNED_JOBS';
export const UPDATE_PARTNER = 'UPDATE_PARTNER';

export const GET_PARTNER_PARTICIPANTS = 'GET_PARTNER_PARTICIPANTS';
export const GET_PARTNER_PARTICIPANTS_SUCCESS =
  'GET_PARTNER_PARTICIPANTS_SUCCESS';

export const PARTNER_VALIDATE_SUBDOMAIN = 'PARTNER_VALIDATE_SUBDOMAIN';
export const PARTNER_VALIDATE_EMAIL = 'PARTNER_VALIDATE_EMAIL';
export const PARTNER_VALIDATE_PHONE = 'PARTNER_VALIDATE_PHONE';

export const REVIEW_PARTNER = 'REVIEW_PARTNER';

export const PARTNER_ADD_JOB = 'PARTNER_ADD_JOB';
export const PARTNER_REMOVE_JOB = 'PARTNER_REMOVE_JOB';

export const PARTNER_GET_INFO = 'PARTNER_GET_INFO';
export const PARTNER_GET_INFO_SUCCESS = 'PARTNER_GET_INFO_SUCCESS';
