export const STATE_NAME = 'CLIENT';

export const GET_CLIENT_DETAIL = 'GET_CLIENT_DETAIL';
export const GET_CLIENT_DETAIL_SUCCESS = 'GET_CLIENT_DETAIL_SUCCESS';

export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';

export const CREATE_CLIENT = 'CREATE_CLIENT';

export const UPDATE_CLIENT = 'UPDATE_CLIENT';

export const DELETE_CLIENT = 'DELETE_CLIENT';

export const CLIENT_REJECT = 'CLIENT_REJECT';

export const CHECK_CLIENT_NAME = 'CHECK_CLIENT_NAME';
