export const STATE_NAME = 'EMPLOYEE';

export const INVITE_EMPLOYEE = 'INVITE_EMPLOYEE';
export const REGISTER_INVITE_EMPLOYEE = 'REGISTER_INVITE_EMPLOYEE';
export const GET_INVITE_EMPLOYEE_INFO = 'GET_INVITE_EMPLOYEE_INFO';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const ADD_EMPLOYEE_TO_PROJECT = 'ADD_EMPLOYEE_TO_PROJECT';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
