export const DOCUMENT = 'DOCUMENT';

export const GET_ALL_FILE = {
  PROCESS: 'GET_ALL_FILE_PROCESS',
  SUCCESS: 'GET_ALL_FILE_SUCCESS',
};

export const UPDATE_JOB_DOCUMENT_FILE = 'UPDATE_JOB_DOCUMENT_FILE';

export const DELETE_FILE = {
  PROCESS: 'DELETE_FILE_PROCESS',
  SUCCESS: 'DELETE_FILE_SUCCESS',
};
