export const STATE_NAME = 'JOB';

export const CREATE_JOB = 'CREATE_JOB';
export const REMOVE_JOB = 'REMOVE_JOB';
export const UPDATE_JOB = 'UPDATE_JOB';

export const INVITE_PARTNER = 'JOB_INVITE_PARTNER';
export const GET_JOB = 'GET_JOB';
export const GET_ASSIGNED_JOB_DETAIL = 'GET_ASSIGNED_JOB_DETAIL';
export const GET_ASSIGNED_JOBS = 'GET_ASSIGNED_JOBS';
export const GET_ASSIGNED_JOBS_SUCCESS = 'GET_ASSIGNED_JOBS_SUCCESS';
export const CREATE_JOB_DOCUMENTS = 'CREATE_JOB_DOCUMENTS';
export const JOB_VALIDATE_NAME = 'JOB_VALIDATE_NAME';
export const GET_JOB_DETAIL_INVITATION = 'GET_JOB_DETAIL_INVITATION';
export const DELETE_JOB_INVITATION = 'DELETE_JOB_INVITATION';
export const UPDATE_JOB_INVITATION = 'UPDATE_JOB_INVITATION';
export const REMOVE_PARTICIPANT_JOB = 'REMOVE_PARTICIPANT_JOB';
export const COMPLETE_JOB = 'COMPLETE_JOB';
export const GET_SHARED_JOB_DETAIL = 'GET_SHARED_JOB_DETAIL';
export const JOB_UPDATE_DURATION = 'JOB_UPDATE_DURATION';
