export const STATE_NAME = 'AUTH';

export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const GET_USER_INFO = 'GET_USER_INFOs';

export const VERIFY_EMAIL_OR_PHONE = 'VERIFY_EMAIL_OR_PHONE';
export const VERIFY_EMAIL_OR_PHONE_SUCCESS = 'VERIFY_EMAIL_OR_PHONE_SUCCESS';

export const CONFIRM_VERIFY_EMAIL_OR_PHONE = 'CONFIRM_VERIFY_EMAIL_OR_PHONE';

export const REGISTER_USER = 'REGISTER_USER';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REQUEST_FORGOT_PASSWORD = 'REQUEST_FORGOT_PASSWORD';

export const REQUEST_CONFIRM_USER = 'REQUEST_CONFIRM_USER';
export const CONFIRM_USER = 'CONFIRM_USER';

export const RESET_PASSWORD = 'RESET_PASSWORD';

export const GET_CURRENT_USER_PROFILE = 'GET_CURRENT_USER_PROFILE';
export const GET_CURRENT_USER_PROFILE_SUCCESS = 'GET_CURRENT_USER_PROFILE_SUCCESS';

export const GET_EMAIL_BY_PHONE = 'GET_EMAIL_BY_PHONE';
export const REQUEST_GET_EMAIL_BY_PHONE = 'REQUEST_GET_EMAIL_BY_PHONE';
