export const STATE_NAME = 'INQUIRY';

export const GET_INQUIRY = 'GET_INQUIRY';
export const GET_INQUIRY_SUCCESS = 'GET_INQUIRY_SUCCESS';
export const CHANGE_INQUIRY_STATUS = 'CHANGE_INQUIRY_STATUS';
