export const STATE_NAME = 'CONTRACT';

export const CREATE_CONTRACT = 'CREATE_CONTRACT';
export const REMOVE_CONTRACT = 'REMOVE_CONTRACT';
export const UPDATE_CONTRACT = 'UPDATE_CONTRACT';
export const GET_CONTRACTS = 'GET_CONTRACTS';
export const GET_CONTRACTS_SUCCESS = 'GET_CONTRACTS_SUCCESS';
export const GET_CONTRACT = 'GET_CONTRACT';
export const GET_CONTRACT_PATH = 'GET_CONTRACT_PATH';
export const SIGN_CONTRACT = 'SIGN_CONTRACT';
export const SIGN_CONTRACT_DOCUSIGN = 'SIGN_CONTRACT_DOCUSIGN';
export const VERIFY_CONTRACT = 'VERIFY_CONTRACT';

export const CREATE_CONTRACT_FROM_TEMPLATE = 'CREATE_CONTRACT_FROM_TEMPLATE';
export const UPDATE_CONTRACT_FROM_TEMPLATE = 'UPDATE_CONTRACT_FROM_TEMPLATE';
