export const STATE_NAME = 'TASK';

export const CREATE_TASK = 'CREATE_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';

export const GET_TASKS = 'GET_TASKS';

export const GET_ALL_TASKS = 'GET_ALL_TASKS';

export const GET_TASK = 'GET_TASK';

export const PUBLIC_GET_ASSIGNED_TASK_DETAIL = 'PUBLIC_GET_ASSIGNED_TASK_DETAIL';
export const PUBLIC_UPDATE_TASK_ASSIGNED = 'PUBLIC_UPDATE_TASK_ASSIGNED';