export const STATE_NAME = 'DYNAMIC_REPORT';

export const GET_DYNAMIC_REPORT = 'GET_DYNAMIC_REPORT';
export const GET_DYNAMIC_REPORT_SUCCESS = 'GET_DYNAMIC_REPORT_SUCCESS';

export const EXPORT_TO_CSV = 'EXPORT_TO_CSV';
